config/routes.rb
Rails.application.routes.draw do

root to: "home#index"

devise_for :users
resources :users, :only => [:show]
post '/', to: 'home#show', as: 'show'

resources :photos do
  resources :tags
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :tags

  has_attached_file :imgfile, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :imgfile, content_type: /\Aimage\/.*\z/
  validates :title, :presence => true
  validates :details, :presence => true



end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :photo

  validates :name, :presence => true

  def findTaggedPhotos
    photos = Photo.all
    photoArray = []
    photos.each do |photo|
      photo.tags.each do |tag|
        if tag.name == self.name
        photoArray.push(photo)
        end
      end
    end
    return photoArray
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
# before_commit :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

 private
   def require_login
     unless current_user
       redirect_to root_path
     end
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @photos = Photo.all
    # @user = current_user      # filtering by user
    # @photos = @user.photos
  end

  def show
    @photoSearchResults = Photo.basic_search(params[:query])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController



  def index
    # @photos = Photo.all
    @user = current_user      # filtering by user
    @photos = @user.photos
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(:title => photo_params[:title], :details => photo_params[:details], :imgfile => photo_params[:imgfile], :user_id => current_user.id)
    if @photo.save
      flash[:notice] = "Photo added!"
      redirect_to photos_path
    else
      flash[:notice] = "Photo not added!"
      render :new
    end
  end

  def edit
      @photo = Photo.find(params[:id])
    end

    def update
      @photo = Photo.find(params[:id])
      if @photo.update(photo_params)
        flash[:notice] = "Photo updated!"
        redirect_to photos_path
      else
        render :edit
      end
    end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:notice] = "Photo deleted!"
    redirect_to photos_path
  end

private
  def photo_params
    params.require(:photo).permit(:title, :details, :imgfile)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def show
      @photo = Photo.find(params[:photo_id])
      tag = Tag.find(params[:id])
      @photoArray = tag.findTaggedPhotos
    end

    def new
      @photo = Photo.find(params[:photo_id])
      @tag = @photo.tags.new
    end

    def create
      @photo = Photo.find(params[:photo_id])
      @tag = @photo.tags.new(tag_params)
      if @tag.save
        flash[:notice] = "Tag added!"
        redirect_to photos_path
      else
        flash[:notice] = "Tag not added!"
        render :new
      end
    end

    def edit
       @photo = Photo.find(params[:photo_id])
        @tag = Tag.find(params[:id])
      end

      def update
        @photo = Photo.find(params[:photo_id])
        @tag = Tag.find(params[:id])
        if @tag.update(tag_params)
          flash[:notice] = "Tag updated!"
          redirect_to photo_path(@photo.id)
        else
          render :edit
        end
      end

    def destroy
      @photo = Photo.find(params[:photo_id])
      @tag = Tag.find(params[:id])
      @tag.destroy
      flash[:notice] = "Tag deleted!"
      redirect_to photo_path(@photo)
    end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/home/index.html.erb
<h1>Flickr Home</h1>

<%= form_tag(show_path, method: 'post', class:'navbar-form navbar-right') do %>
    <div class="form-group">
      <%= text_field_tag :query, "", class: "form-control", placeholder: "Search" %>
    </div>
    <button type="submit" class="btn btn-info"> Search
    </button>
  <% end %>



<% if @photos.any? %>
<% @photos.each do |photo| %>
 <li>
   <div class="card blue-grey darken-1">
     <div class="card-content white-text">
    <%= image_tag photo.imgfile, :class => "photo-size" %>
    <%= link_to photo.title, photo_path(photo)%>
    </div>
  </div>

 </li>
 <% end %>
 <% else %>
<p>
  There are no photos
</p>
<% end %>

app/views/home/search.html.erb
<% if @photoSearchResults %>
  <% @photoSearchResults.each do |photo| %>
  <%= image_tag photo.imgfile %>
  <% end %>
<% else %>
  <p>
    There are no search results.
  </p>
<% end %>

app/views/home/show.html.erb
<% if @photoSearchResults %>
  <% @photoSearchResults.each do |photo| %>
  <%= image_tag photo.imgfile %>
  <% end %>
<% else %>
  <p>
    There are no search results.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPICODUS Flickr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <div class="nav-wrapper black">

          <ul>
          <li><a href="/" class=" logo-size">Flickr</a></li>

          <% if current_user %>
          <li><%= link_to "You", photos_path, :class => 'main-links' %> </li>
          <div class="right">
            <li><%= current_user.email %></li>
            <li><%= link_to "Log-out", destroy_user_session_path, method: "delete" %></li>
          </div>
          <% else %>
            <div class="right">
              <li>  <%= link_to "Log-in", new_user_session_path %> |</li>
              <li><%= link_to "Signup", new_user_registration_path %></li>
            </div>
          <% end %>
          </ul>
        </div>
    </nav>
    <div class="container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <%= f.label :title,'Image Title' %>
  <%= f.text_field :title, :class => 'form-control' %>
  <%= f.label :details,'Image Details' %>
  <%= f.text_field :details, :class => 'form-control' %>
  <%= f.label :imgfile, 'Image File' %>
  <%= f.file_field :imgfile %>
  <%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>
<%= render "form" %>

app/views/photos/index.html.erb
<h1>Index</h1>

<div class="well">

<% if @photos.any? %>
<% @photos.each do |photo| %>
 <li>
   <div class="card white">
     <div class="card-title">
       <%= link_to photo.title, photo_path(photo) %> <br>
          <%= time_ago_in_words(photo.created_at, :class => "test" ) %> ago
        <!-- <h5><%= photo.created_at.strftime("%m-%d-%Y")%></h5> -->
     </div>
     <div class="card-content">
    <%= link_to image_tag(photo.imgfile, :class => "photo-size"), photo_path(photo) %>
       <div class="center">
         <%= photo.details %>
       </div>
   </div>
  </div>

 </li>
 <% end %>
 <% else %>
<p>
  There are no photos
</p>
<% end %>
</div>
<br>
<div class ="bar">
</div>
<br>
<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>
<%= render "form" %>

app/views/photos/show.html.erb
<div class="card white darken-1 size-big">
  <div class="card-content white-text">
<%= image_tag @photo.imgfile, :class => "photo-size" %>
<%= @photo.title %>
<%= @photo.user.email %>
<br>
<% if @photo.tags.any? %>
  <% @photo.tags.each do |tag| %>
  <div class="chip">


  <%= link_to tag.name, photo_tag_path(@photo, tag.id) %> |
  <%= link_to "Delete X", photo_tag_path(@photo, tag.id), :data => {:confirm => "Are you sure?",:method => "delete"}%> |
  <%= link_to "Rename", edit_photo_tag_path(@photo, tag.id) %> <br>
    </div>
  <% end %>
  <% else %>
  <p>
    No tags
  </p>
<% end %>
</div>
</div>
<% if current_user == @photo.user  %>
<%= link_to "Edit", edit_photo_path %>
<%= link_to "Delete photo", photo_path(@photo, @photo.id), :data => {:confirm => "Are you sure?",:method => "delete"}%>
<%= link_to "Add Tag", new_photo_tag_path(@photo) %>
<% end %>

app/views/tags/_form.html.erb
<%= form_for [@photo, @tag] do |f| %>
  <%= f.label :name,'Tag Name' %>
  <%= f.text_field :name, :class => 'form-control' %>
  <%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>
<%= render "form" %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<%= render "form" %>

app/views/tags/show.html.erb
<h1>Results</h1>
<% if @photoArray.any? %>
  <% @photoArray.each do |photo| %>
  <%= image_tag photo.imgfile %>
  <% end %>
<% else %>
  <p>
    There are no photos with this tag name.
  </p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>